import { Release } from "./types";

export const releases: Release[] = [
  {
    id: 1,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 2,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 3,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 4,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 5,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 10,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 20,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 30,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 40,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
  {
    id: 50,
    title: "Flashback",
    artists: ["Jeremy Sylvester", "Maria Labelle"],
    releaseDate: "2024-03-22",
    href: "TIN056",
    catalog: "TIN056",
    imageUrl:
      "https://geo-media.beatport.com/image_size/1400x1400/8962c817-9e8f-4b5c-b3ea-5ad62d92d07f.jpg",
    tracks: [
      {
        id: 1,
        title: "90s man",
        artists: ["Jeremy Sylvester"],
        length: 348,
        BPM: 132,
        key: "G Minor",
      },
      {
        id: 1,
        title: "Flashback",
        artists: ["Jeremy Sylvester"],
        length: 330,
        BPM: 130,
        key: "G Minor",
      },
    ],
  },
];
