import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/common/Navigation";
import {
  druk,
  drukText,
  drukWide,
  drukTextWide,
  drukCondensed,
  drukXCondensed,
  drukXXCondensed,
  youth,
} from "./lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// [&_*]:border [&_*]:border-red-500

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${druk.variable} ${drukText.variable} ${drukWide.variable} ${drukTextWide.variable} ${drukCondensed.variable} ${drukXCondensed.variable} ${drukXXCondensed.variable} ${youth.variable}`}
    >
      {/* cursor-none */}
      <body
        className={`relative h-full w-full overflow-x-hidden scroll-smooth bg-black text-white selection:bg-black selection:text-white`}
      >
        <div className="relative h-full w-full">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
