import type { Metadata } from "next";
import "./globals.css";
import {
  druk,
  drukText,
  drukWide,
  drukTextWide,
  drukCondensed,
  drukXCondensed,
  drukXXCondensed,
  youth,
} from "./lib/fonts";
import Navigation from "./components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// [&_*]:border [&_*]:border-red-500

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${druk.variable} ${drukText.variable} ${drukWide.variable} ${drukTextWide.variable} ${drukCondensed.variable} ${drukXCondensed.variable} ${drukXXCondensed.variable} ${youth.variable}`}
    >
      {/* cursor-none */}
      <body
        className={`relative overflow-x-hidden scroll-smooth selection:bg-black selection:text-white`}
      >
        <div className="relative min-h-screen w-full bg-gradient-to-t from-gray-100 to-gray-300">
          {/* <Navigation /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
